# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

jobs:
- job: armkit
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    # Node.js tool installer
    # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
    - task: NodeTool@0
      inputs:
        versionSpec: '13.x'
        checkLatest: true

    # yarn install
    - bash: |
        yarn install
        yarn build
      displayName: 'Yarn install'
      failOnStderr: true
  
      # yarn lint run
    - bash: |
        yarn lint
      displayName: 'Run yarn lint'
      workingDirectory: examples/basic 
      displayName: 'Yarn lint'
      failOnStderr: true

      # yarn test run
    - bash: |
        yarn test
      workingDirectory: examples/basic 
      displayName: 'Yarn test'
      failOnStderr: true      
