# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
- job: armkit_generate
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    # Node.js tool installer
    # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
    - task: NodeTool@0
      inputs:
        versionSpec: '13.x' 
        checkLatest: true
    # npm dpendencies installer
    - script: npm install
      workingDirectory: $(Agent.BuildDirectory)/examples/basic/
      displayName: 'Run npm install in root_folder'
    # yarn setup installer
    - script: yarn
      workingDirectory: $(Agent.BuildDirectory)/examples/basic/
      displayName: 'Run yarn build in root_folder'
    # arnkit generate run      
    - script: ./node_modules/armkit-cli/bin/armkit generate
      displayName: 'Run armkit generate' 
      workingDirectory: $(Agent.BuildDirectory)/examples/basic/

