# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- development

jobs:
- job: armkit_generate
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    # Node.js tool installer
    # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
    - task: NodeTool@0
      inputs:
        versionSpec: '13.x' 
        checkLatest: true
    - script: |
        pwd
        ls -l 
      workingDirectory: $(Agent.BuildDirectory)
      displayName: List contents of a folder
    # arnkit generate run      
    - bash: |
        set -x
        cd examples/basic/
        pwd
        npm install && yarn
        ./node_modules/armkit-cli/bin/armkit generate
      displayName: 'Run armkit generate' 

