# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- devopment

jobs:
- job: armkit_generate
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - script: npm install
      displayName: 'Run npm install in root_folder'
    - script: yarn
      displayName: 'Run yarn build in root_folder'
    - script: |
        cd examples/basic/
        ./node_modules/armkit-cli/bin/armkit generate
      displayName: 'Run armkit generate' 

